name: Ubuntu
on: [push, pull_request, workflow_dispatch]
jobs:
  UbuntuRun:
    runs-on: ubuntu-latest
    steps:      
      - run: sudo apt-get update
      - run: sudo apt-get install -y xorg-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev      
      - name: Checkout
        uses: actions/checkout@v3            
      - name: Create build directory
        run: mkdir ${{github.workspace}}/build      
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../
      - name: Run make
        working-directory: ${{github.workspace}}/build
        run: make -j 4
      #- name: Run Test
      #  working-directory: ${{github.workspace}}/build
      #  run: ctest --no-compress-output -T Test -C Release --output-on-failure
